trigger:
- master

jobs:
  - job: measure
    displayName: "Run wasm-bindgen crate tests (unix)"
    steps:
      - template: ci/azure-install-rust.yml
      - script: cargo run out.json
        displayName: "Collect benchmark data"
