trigger:
- master

jobs:
  - job: build_collector
    displayName: "Build the collector binary"
    steps:
      - template: ci/azure-install-rust.yml
      - script: |
          set -ex
          cargo build
          strip -g target/debug/collector
          strip -g target/debug/site
          mkdir artifact
          cp target/debug/collector artifact/
          cp target/debug/site artifact/
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: collector
          targetPath: artifact

  - job: collect_data
    dependsOn: build_collector
    displayName: "Gather benchmark data"
    strategy:
      matrix:
        twiggy:
          benchmark: twiggy
        rust_webpack_template:
          benchmark: rust_webpack_template
        game_of_life:
          benchmark: game_of_life
    steps:
      - template: ci/azure-install-rust.yml
        parameters:
          toolchain: nightly
      - script: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
        displayName: "Install wasm-pack"
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: collector
          targetPath: ./collector
      - script: chmod +x ./collector/collector && ./collector/collector measure $(benchmark).json $(benchmark)
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: $(benchmark)
          targetPath: $(benchmark).json

  - job: publish
    dependsOn: collect_data
    displayName: "Collate and publish benchmark data"
    steps:
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: collector
          targetPath: ./collector
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: twiggy
          targetPath: ./
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: rust_webpack_template
          targetPath: ./
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: game_of_life
          targetPath: ./
      - script: chmod +x ./collector/collector && ./collector/collector merge out.json *.json
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: dataset
          targetPath: out.json
      - script: |
          set -e
          source ci/setup-git.sh
          git clone git@github.com:rustwasm/wasm-weight-tracker-data
          mkdir -p wasm-weight-tracker-data/builds
          gzip -9 out.json
          date=$(date +'%Y-%m-%d-%H%M')
          mv out.json.gz wasm-weight-tracker-data/builds/$date.json.gz
          cd wasm-weight-tracker-data
          git add .
          git commit -m "More data"
          git push
        displayName: "Push new data to data repo"
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        env:
          GITHUB_DEPLOY_KEY: '$(GITHUB_DEPLOY_KEY)'

  - job: website
    dependsOn: publish
    displayName: "Push Website"
    steps:
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: collector
          targetPath: ./collector
      - script: chmod +x ./collector/site && ./collector/site --git tmp html/out.json
      - script: |
          set -e
          source ci/setup-git.sh
          cd html
          git init
          git add .
          git commit -m "Deploy $BUILD_SOURCEVERSION"
          git push git@github.com:rustwasm/wasm-weight-tracker master:gh-pages -f
        displayName: "Push to gh-pages"
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        env:
          GITHUB_DEPLOY_KEY: '$(GITHUB_DEPLOY_KEY)'
