[package]
name = "shared"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ['derive'] }
log = "0.4"
failure = "0.1"
